CREATE PROCEDURE GET_TWOSETS_CUSTOMERINFO
(
   P_CREDITLINEAMOUNT IN INTEGER,
   CURSOR1_ IN OUT TYPES.REF_CURSOR,
   CURSOR2_ IN OUT TYPES.REF_CURSOR 
)
AS
BEGIN
   OPEN CURSOR1_ FOR
      SELECT * FROM CROSSSELLCUSTOMERS 
      WHERE CREDITLINEAMOUNT >= P_CREDITLINEAMOUNT;
    
  OPEN CURSOR2_ FOR
      SELECT * FROM CROSSSELLCUSTOMERS 
       WHERE CARDTYPE = 'Platinum' AND CREDITLINEAMOUNT >= P_CREDITLINEAMOUNT;    
END;
