CREATE OR REPLACE PROCEDURE GET_TWOSETS_CUSTOMERINFO
(
   P_CREDITLINEAMOUNT IN INTEGER,   
)
AS

CURSOR CURSOR1_ IS 
  SELECT CAMPO1, CAMPO2 
  FROM TABLA
  WHERE CAMPO3 = P_CREDITLINEAMOUNT;
BEGIN

FORALL R1 IN CURSOR1_ LOOP
insert into tabla2(VALOR,DESCRIPCION)
values(R1.CAMPO1, R2.CAMPO2);
END LOOP;
  COMMIT;
END;
